apiVersion: apps/v1
kind: Deployment
metadata:
  name: fendry
  labels:
  desc: fendry-app-deployment
spec:
  selector:
    matchLabels:
      app: fendry
  template:
    metadata:
      labels:
        app: fendry
    spec:
      containers:
      - name: fendry-main
        image: docker.io/fensaurav225986/fendrydry:latest
        ports:
        - containerPort: 8000
